# Matrices

- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>

![](img/QC_Math_Banner.png "")

<font color="red">**Notice**</font>: All materials herein were <font color="red">**curated**</font> by **Matthew R. Versaggi (profversaggi@gmail.com)** and are released into the open source to foster growth and welfare of expanding the Quantum Computing domain - the only obligation one incurs when using, copying, distributing or referencing this is to kindly reference the author and send me an email so I know how useful the material is to you.

#### <font color="red">Recommendations</font>: 

> **<font color="blue">It's highly recommended to take structured QC Math courses <font color="red">like</font>:</font>**
> #### Math Prerequisites for Quantum Computing
> - https://www.udemy.com/course/mathematics-prerequisites-for-quantum-computing-and-quantum-physics/

> #### Advanced Math for Quantum Computing
> - https://www.udemy.com/course/qc201-advanced-math-for-quantum-computing-mathematics-physics/



#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">Amelie Schreiber</font>**
- Article: https://towardsdatascience.com/quantum-computing-for-the-newb-5e0737e3ca4
- Course: https://the-singularity-research.github.io/linear_algebra_for_quantum_computing/
- GitHub: https://github.com/The-Singularity-Research/linear_algebra_for_quantum_computing

> **<font color="blue">QWorld</font>**
- Site: https://qworld.lu.lv/
- GitLab: https://gitlab.com/qkitchen/basics-of-quantum-computing

## Matricies


### <font color="red">**Background Information**</font>: 

- **Immersive Linear Algebra**: - http://immersivemath.com/ila/index.html
- **Interactive Matrix**: -https://shad.io/MatVis/
- **Interactive Math - Matricies**: -https://www.intmath.com/matrices-determinants/matrix-addition-multiplication-applet.php



### Imports and Dependencies

We will primarily be using NumPy in this section. 

In [2]:
import numpy as np

### <font color="red">**Why this is important**</font>: 

#### Matrices form the foundation for quantum gates
- Operations on qubits that *move the points representing states around the Bloch sphere*. 


> Matrices are also called **operators or quantum gates** in the context of quantum computing. 
- They can operate on a single qubit, or on many qubits simultaneously. 


> The matrix operators (or gates) we will be using most are known as *unitary operators* or *unitary matrices*. 

In this section we will discuss **basic matrix algebra** and **define unitary matrices**. 

We have already seen two ways of realizing matrices in Python. 

Suppose we have the following **$2 \times 2$ matrix**

<BR>
<font color="blue">

\begin{align}
M = \begin{pmatrix}
2-i & -3 \\
-5i & 2
\end{pmatrix}
\end{align}

</font>
<BR>

- We can define this matrix as a NumPy **array**, or as a **matrix** in Python.

#### NumPy Array

In [3]:
M = np.array([[2-1j, -3],
              [-5j, 2]])

print(M)

[[ 2.-1.j -3.+0.j]
 [-0.-5.j  2.+0.j]]


> Since we may want to compute **Hermitian Conjugates** of matrices, we will **only** be using the matrix data structure.

#### NumPy Matrix

In [20]:
M = np.matrix([[2-1j, -3],
               [-5j, 2]])

print(M)

[[ 2.-1.j -3.+0.j]
 [-0.-5.j  2.+0.j]]


<font color="blue">**Remember**, **Hermitian conjugates** are given by taking the **conjugate transpose** of the **matrix**.</font> 

> This means we compute the complex conjugate of each entry, and then transpose the matrix. 
- Generally, the Hermitian conjugate is denoted by $M^{\dagger}$. 

In [21]:
# Compute the Hermitian Conjugate (aka. Conjugate Transpose)

hc = M.H

print(hc)

[[ 2.+1.j -0.+5.j]
 [-3.-0.j  2.-0.j]]


#### Look at another example of a Hermitian conjugate (aka. conjugate transpose). 

In [6]:
B = np.matrix([[1, -3j, 5, 2], 
               [1-1j, 1, 3, 7j]])

B_hc = B.H

print(B_hc)

[[ 1.-0.j  1.+1.j]
 [-0.+3.j  1.-0.j]
 [ 5.-0.j  3.-0.j]
 [ 2.-0.j  0.-7.j]]


#### This is a $4 \times 2$ matrix which came from the $2 \times 4$ matrix $B$. 

- Notice *all of its entries have also been conjugated*. 
- We can also **multiply matrices so long as the dimensions match appropriately**. 

> In particular, to multiply two matrices $A$ and $B$, the matrix must be an $n \times p$ matrix and the matrix $B$ must be a $p \times m$ matrix. 
- The result is an $n \times m$ matrix. 


#### For example:

In [7]:
# Define a 3x2 matrix:

A = np.matrix([[2j, -5],
               [3-5j, 1], 
               [5, 4j]])


# Define a 2x4 matrix:

B = np.matrix([[1, -3j, 5, 2], 
               [1-1j, 1, 3, 7j]])


#Taking the product of a (3x2) and (2x4) matrix will give a 3x4 matrix:

np.dot(A, B)

matrix([[ -5. +7.j,   1. +0.j, -15.+10.j,   0.-31.j],
        [  4. -6.j, -14. -9.j,  18.-25.j,   6. -3.j],
        [  9. +4.j,   0.-11.j,  25.+12.j, -18. +0.j]])

> - If we are using the **matrix definition** instead of the **array definition**, then we can also **multiply the two matrices** as follows:

### Multiply two matrices

In [7]:
A*B

matrix([[ -5. +7.j,   1. +0.j, -15.+10.j,   0.-31.j],
        [  4. -6.j, -14. -9.j,  18.-25.j,   6. -3.j],
        [  9. +4.j,   0.-11.j,  25.+12.j, -18. +0.j]])

#### If we define the two matrices as arrays, this will not work and will return an <font color="red">error</font>. 

> We *won't* often be **adding** and **subtracting** matrices in the context of quantum computing but these operations are well defined for matrices of the same size. 

The Python code is exactly what you would expect it to be. 

- Let's define two matrices of the same size. 

In [9]:
M = np.matrix([[1, 2, 3], 
               [1j, 2j, 3j]])


N = np.matrix([[2, 4, 6],
               [-2j, -4j, -6j]])

#### Addition

In [11]:
M+N

matrix([[3.+0.j, 6.+0.j, 9.+0.j],
        [0.-1.j, 0.-2.j, 0.-3.j]])

#### Subtraction

In [12]:
M-N

matrix([[-1.+0.j, -2.+0.j, -3.+0.j],
        [ 0.+3.j,  0.+6.j,  0.+9.j]])

We can also multiply matrices by scalars.

#### Scalar Multiplication

In [13]:
3*M

matrix([[3.+0.j, 6.+0.j, 9.+0.j],
        [0.+3.j, 0.+6.j, 0.+9.j]])

# <font color="red">Graded Exercises</font>  for use <font color="blue">with structured courses.</font>

## Matricies

#### <font color="blue">*This work will take some time, so block off enough time to adequately cover it*</font>. 


- Go through the **entire** JNB and complete each of the exercises, including any supplementary Video's - hand in completed <font color="red">**PDF**</font> from this JNB once finished.


- Step through the code for **each** of the above exercises, make sure you can (1) execute it, and (2) know what it does.


- <font color="blue">Complete Challenge Exercises below.</font> **(turn in the JNB)**

## Exercises: Matricies

### <font color="red">Reference Materials</font>.

<BR>
    <font color="blue">
\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}
    

<BR>

- #### I = Identity
- #### X = NOT
- #### Y = Pauli-Y
- #### Z = Pauli-Z
- #### H = Hadamard

</font>

> **These are five of the most common single qubit gates used in quantum computing**, and they will be used repeatedly. 

#### <font color="red">1</font>: Identity

In [3]:
I = np.matrix([[1, 0],
               [0, 1]])
I

matrix([[1, 0],
        [0, 1]])

#### <font color="red">2</font>: NOT

In [4]:
X = np.matrix([[0, 1],
               [1, 0]])
X

matrix([[0, 1],
        [1, 0]])

#### <font color="red">3</font>: Pauli-Y

In [9]:
Y = np.matrix([[0, 1j],
               [-1j, 0]])
Y

matrix([[ 0.+0.j,  0.+1.j],
        [-0.-1.j,  0.+0.j]])

#### <font color="red">4</font>: Pauli-Z

In [11]:
Z = np.matrix([[1, 0],
               [0, -1]])
Z

matrix([[ 1,  0],
        [ 0, -1]])

#### <font color="red">5</font>: Hadamard

In [14]:
H = (1/np.sqrt(2))* np.matrix([[1, 1],
                                [1, -1]])
H

matrix([[ 0.70710678,  0.70710678],
        [ 0.70710678, -0.70710678]])

### Write Python code to compute the following (1 - 10) Matrix Multiplications:


### <font color="red">1</font>:  $XY$

#### <font color="red">This first one is done for you</font>.

#### Check the shape of the matricies first to make sure the dimensions match appropriately

In [16]:
X.shape

(2, 2)

In [17]:
Y.shape

(2, 2)

#### Multiply the two matrices

In [18]:
X*Y

matrix([[0.-1.j, 0.+0.j],
        [0.+0.j, 0.+1.j]])

### <font color="red">2</font>:  $YX$

### <font color="red">3</font>:  $YZ$

### <font color="red">4</font>:  $ZY$

### <font color="red">5</font>:  $HX$

### <font color="red">6</font>:  $YH$

### <font color="red">7</font>:  $XYZ$

### <font color="red">8</font>:  $YZX$

### <font color="red">9</font>:  $ZXY$

### <font color="red">10</font>:  $XHY$

![the-end](img/the-end.png "the-end")