# Tensor Products of Matrices

- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>

![](img/QC_Math_Banner.png "")

<font color="red">**Notice**</font>: All materials herein were <font color="red">**curated**</font> by **Matthew R. Versaggi (profversaggi@gmail.com)** and are released into the open source to foster growth and welfare of expanding the Quantum Computing domain - the only obligation one incurs when using, copying, distributing or referencing this is to kindly reference the author and send me an email so I know how useful the material is to you.

#### <font color="red">Recommendations</font>: 

> **<font color="blue">It's highly recommended to take structured QC Math courses <font color="red">like</font>:</font>**
> #### Math Prerequisites for Quantum Computing
> - https://www.udemy.com/course/mathematics-prerequisites-for-quantum-computing-and-quantum-physics/

> #### Advanced Math for Quantum Computing
> - https://www.udemy.com/course/qc201-advanced-math-for-quantum-computing-mathematics-physics/



#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">Amelie Schreiber</font>**
- Article: https://towardsdatascience.com/quantum-computing-for-the-newb-5e0737e3ca4
- Course: https://the-singularity-research.github.io/linear_algebra_for_quantum_computing/
- GitHub: https://github.com/The-Singularity-Research/linear_algebra_for_quantum_computing

> **<font color="blue">QWorld</font>**
- Site: https://qworld.lu.lv/
- GitLab: https://gitlab.com/qkitchen/basics-of-quantum-computing

## Imports

As usual, we will need NumPy. So, let's import it now. 

In [2]:
import numpy as np

### <font color="red">**Why this is important**</font>: 


#### This discussion is about how to take tensor products of matrices in order to later build quantum gates that operate on <font color="red">many</font> qubits at once. 

> Understanding the **basics of tensor products of matrices** is **fundamental to understanding quantum logic gates** and **quantum circuits**. 


> ### For the tensor product of two $2 \times 2$ matrices, <font color="red">the general rule</font> is as follows:


<BR>
<font color="blue">

\begin{align}
\begin{pmatrix}
a & b \\
c & d
\end{pmatrix} \otimes 
\begin{pmatrix}
x & y \\
z & w
\end{pmatrix} = 
\begin{pmatrix}
a \begin{pmatrix}
x & y \\
z & w
\end{pmatrix} & b \begin{pmatrix}
x & y \\
z & w
\end{pmatrix} \\
c \begin{pmatrix}
x & y \\
z & w
\end{pmatrix} & d \begin{pmatrix}
x & y \\
z & w
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
ax & ay & bx & by \\
az & aw & bz & bw \\
cx & cy & dx & dy \\
cz & cw & dz & dw
\end{pmatrix}
\end{align}

</font>
<BR>

> ### Here is a basic <font color="red">numerical</font> example:


<BR>
<font color="blue">

\begin{align}
\begin{pmatrix}
2 & 3 \\
6 & 1
\end{pmatrix} \otimes
\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix} = 
\begin{pmatrix}
2 \begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix}& 3\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix} \\
6\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix} & 1\begin{pmatrix}
7 & 10 \\
9 & 4
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
14 & 20 & 21 & 30 \\
18 & 8 & 27 & 12 \\
42 & 60 & 7 & 10 \\
54 & 24 & 9 & 4
\end{pmatrix}
\end{align}

</font>
<BR>

> - We can again use the **'np.kron()'** function to perform this computation in **Python**, just as we did for qubit state vectors. 

In [2]:
A = np.matrix([[2, 3],
               [6, 1]])

B = np.matrix([[7, 10], 
               [9, 4]])

np.kron(A,B)

matrix([[14, 20, 21, 30],
        [18,  8, 27, 12],
        [42, 60,  7, 10],
        [54, 24,  9,  4]])

**In quantum computing**, if we have <font color="red">**basis states**</font>  such as "<font color="blue">**|010>**</font>"

<BR>
<font color="blue">
    
\begin{align}
|010\rangle &= |0\rangle \otimes |1\rangle \otimes |0\rangle \\
&= \begin{pmatrix}
1\\0
\end{pmatrix} \otimes 
\begin{pmatrix}
0\\1
\end{pmatrix} \otimes 
\begin{pmatrix}
1\\0
\end{pmatrix} \\
&= \begin{pmatrix}
0\\0\\1\\0\\0\\0\\0\\0
\end{pmatrix}
\end{align}

</font>
<BR>

#### we can operate on them using <font color="red">**tensor product of operators**</font>. 

In particular, to operate on a <font color="red">**three**</font>  **qubit basis state** such at this, we need the **tensor product** of <font color="red">**three**</font> $2 \times 2$ matrices. 



**For example**, with the following <font color="red">**four**</font> operators:

<BR>
<font color="blue">
    
\begin{align}
I = \begin{pmatrix} 1&0 \\ 0&1 \end{pmatrix}, \quad
X = \begin{pmatrix} 0&1 \\ 1&0 \end{pmatrix}, \quad
Y = \begin{pmatrix} 0&i \\ -i&0 \end{pmatrix}, \quad
Z = \begin{pmatrix} 1&0 \\ 0&-1 \end{pmatrix}, \quad
H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1&1 \\ 1&-1 \end{pmatrix}
\end{align}

</font>
<BR>


We can **form tensor products of matrices (gates)** such as:

<BR>
<font color="blue" size=4>
- $H \otimes X \otimes I$ 
- $Z \otimes Z \otimes H$
</font>
<BR>    
    
#### and <font color="red">**any**</font> other <font color="red">**three**</font> matrix combination you might dream up. 


> - Let's define a basis state **$|01\rangle$** and **compute a few operators** that will operate on this **basis state**:

### Define the basis state |01>

In [8]:
# Define the basis state |01>

u = np.matrix([[1],
               [0]])

d = np.matrix([[0],
               [1]])


# Basis State "ud" (|01>)
ud = np.kron(u,d)

print(ud)

[[0]
 [1]
 [0]
 [0]]


### Define the matrices X, Y, Z, and H

In [10]:
# Define the matrices X, Y, Z, and H

X = np.matrix([[0, 1],
               [1, 0]])

Y = np.matrix([[0, -1j], 
               [1j, 0]])

Z = np.matrix([[1, 0],
               [0, -1]])

H = (1/np.sqrt(2))*np.matrix([[1, 1], 
                              [1, -1]])

### Compute the following <font color="blue">**three**</font> <font color="red">**tensor products**</font>:


<BR>
<font color="blue" size=4>

\begin{align}
X \otimes Y, \quad X \otimes Z, \quad H \otimes H
\end{align}

</font>
<BR>

### <font color="blue">**Tensor product**</font>:

<BR>
<font color="blue" size=5>

\begin{align}
X \otimes Y \quad 
\end{align}

</font>
<BR>

In [5]:
print(np.kron(X, Y))

[[0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]


### <font color="blue">**Tensor product**</font>:
<BR>
<font color="blue" size=5>

\begin{align}
\quad X \otimes Z
\end{align}

</font>
<BR>

In [6]:
print(np.kron(X, Z))

[[ 0  0  1  0]
 [ 0  0  0 -1]
 [ 1  0  0  0]
 [ 0 -1  0  0]]


### <font color="blue">**Tensor product**</font>:

<BR>
<font color="blue" size=5>

\begin{align}
\quad H \otimes H
\end{align}

</font>
<BR>

In [7]:
print(np.kron(H, H))

[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


Now, we can compute the <font color="red">**action**</font> of these matrices on the basis state <font color="blue">**$|01\rangle$**</font>   as:

<BR>
<font color="blue">
        
\begin{align}
(X \otimes Y)(|01\rangle) = (X \otimes Y)(|0\rangle \otimes |1\rangle) = X|0\rangle \otimes Y|1\rangle 
\end{align}

\begin{align}
(X \otimes Z)(|01\rangle) = (X \otimes Z)(|0\rangle \otimes |1\rangle) = X|0\rangle \otimes Z|1\rangle 
\end{align}

\begin{align}
(H \otimes H)(|01\rangle) = (H \otimes H)(|0\rangle \otimes |1\rangle) = H|0\rangle \otimes H|1\rangle 
\end{align}

</font>
<BR>


### <font color="blue">**Tensor product(s)**</font>:

In [8]:
XY = np.kron(X, Y)
XZ = np.kron(X, Z)
HH = np.kron(H, H)

### <font color="blue">**Action**</font>: <font color="red">(XY * ud)</font>

<BR>
<font color="blue">
        
\begin{align}
(X \otimes Y)(|01\rangle) = (X \otimes Y)(|0\rangle \otimes |1\rangle) = X|0\rangle \otimes Y|1\rangle 
\end{align}


</font>
<BR>

In [9]:
print(XY * ud)

[[0.+0.j]
 [0.+0.j]
 [0.-1.j]
 [0.+0.j]]


### <font color="blue">**Action**</font>: <font color="red">(XZ * ud)</font>
<BR>
<font color="blue">
        
\begin{align}
(X \otimes Z)(|01\rangle) = (X \otimes Z)(|0\rangle \otimes |1\rangle) = X|0\rangle \otimes Z|1\rangle 
\end{align}


</font>
<BR>

In [10]:
print(XZ * ud)

[[ 0]
 [ 0]
 [ 0]
 [-1]]


### <font color="blue">**Action**</font>: <font color="red">(HH * ud)</font>
<BR>
<font color="blue">

\begin{align}
(H \otimes H)(|01\rangle) = (H \otimes H)(|0\rangle \otimes |1\rangle) = H|0\rangle \otimes H|1\rangle 
\end{align}

</font>
<BR>

In [11]:
print(HH * ud)

[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]


# <font color="red">Graded Exercises</font>  for use <font color="blue">with structured courses.</font>

## Tensor Product Matricies

#### <font color="blue">*This work will take some time, so block off enough time to adequately cover it*</font>. 


- Go through the **entire** JNB and complete each of the exercises, including any supplementary Video's - hand in completed <font color="red">**PDF**</font> from this JNB once finished.


- Step through the code for **each** of the above exercises, make sure you can (1) execute it, and (2) know what it does.


- <font color="blue">Complete Challenge Exercises below.</font> **(turn in the JNB)**

## Exercises: Tensor Product Matricies


#### Write Python code to compute the tensor products (<font color="blue">below</font>):

<BR>
<font color="blue">

0. $X \otimes X$
0. $Z \otimes Y$
0. $H \otimes X$
0. $H \otimes H$

</font>
<BR>

### <font color="red">1</font>: $X \otimes X$

> - ### <font color="red">This first one is done for you</font>.

In [11]:
print(np.kron(X, X))

[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


### <font color="red">2</font>: $Z \otimes Y$

### <font color="red">3</font>: $H \otimes X$

### <font color="red">4</font>: $H \otimes H$

### <font color="red">5a</font>: Write Python code to verify that the "Associative Property" holds with the following Tensor Products: 

<BR>
<font color="blue">

$(H \otimes H) \otimes H$ <font color="red" size=5>=</font> $H \otimes (H \otimes H)$.


</font>
<BR>
    
> - ### <font color="red">This one is done for you</font>.

#### <font color="red">LHS</font>: (Left Hand Side of Equation) - <font color="blue">$(H \otimes H) \otimes H$</font>

In [20]:
LHS = np.kron(np.kron(H, H),H)
LHS

matrix([[ 0.35355339,  0.35355339,  0.35355339,  0.35355339,  0.35355339,
          0.35355339,  0.35355339,  0.35355339],
        [ 0.35355339, -0.35355339,  0.35355339, -0.35355339,  0.35355339,
         -0.35355339,  0.35355339, -0.35355339],
        [ 0.35355339,  0.35355339, -0.35355339, -0.35355339,  0.35355339,
          0.35355339, -0.35355339, -0.35355339],
        [ 0.35355339, -0.35355339, -0.35355339,  0.35355339,  0.35355339,
         -0.35355339, -0.35355339,  0.35355339],
        [ 0.35355339,  0.35355339,  0.35355339,  0.35355339, -0.35355339,
         -0.35355339, -0.35355339, -0.35355339],
        [ 0.35355339, -0.35355339,  0.35355339, -0.35355339, -0.35355339,
          0.35355339, -0.35355339,  0.35355339],
        [ 0.35355339,  0.35355339, -0.35355339, -0.35355339, -0.35355339,
         -0.35355339,  0.35355339,  0.35355339],
        [ 0.35355339, -0.35355339, -0.35355339,  0.35355339, -0.35355339,
          0.35355339,  0.35355339, -0.35355339]])

#### <font color="red">RHS</font>: (Right Hand Side of Equation) - <font color="blue">$H \otimes (H \otimes H)$</font>

In [21]:
RHS = np.kron(H,(np.kron(H, H)))
RHS

matrix([[ 0.35355339,  0.35355339,  0.35355339,  0.35355339,  0.35355339,
          0.35355339,  0.35355339,  0.35355339],
        [ 0.35355339, -0.35355339,  0.35355339, -0.35355339,  0.35355339,
         -0.35355339,  0.35355339, -0.35355339],
        [ 0.35355339,  0.35355339, -0.35355339, -0.35355339,  0.35355339,
          0.35355339, -0.35355339, -0.35355339],
        [ 0.35355339, -0.35355339, -0.35355339,  0.35355339,  0.35355339,
         -0.35355339, -0.35355339,  0.35355339],
        [ 0.35355339,  0.35355339,  0.35355339,  0.35355339, -0.35355339,
         -0.35355339, -0.35355339, -0.35355339],
        [ 0.35355339, -0.35355339,  0.35355339, -0.35355339, -0.35355339,
          0.35355339, -0.35355339,  0.35355339],
        [ 0.35355339,  0.35355339, -0.35355339, -0.35355339, -0.35355339,
         -0.35355339,  0.35355339,  0.35355339],
        [ 0.35355339, -0.35355339, -0.35355339,  0.35355339, -0.35355339,
          0.35355339,  0.35355339, -0.35355339]])

#### TEST: <font color="red">LHS = RHS</font>: (aka. Test <font color="red">ALL</font> Elements of the Matrix for equivalence)

In [29]:
(LHS == RHS).all()

True

### <font color="red">5b</font>: Write Python code to verify that: 

<BR>
<font color="blue">

$X \otimes (X \otimes X)$ <font color="red" size=5>=</font> $(X \otimes X) \otimes X$.

</font>
<BR>
    

### The following defines the basis state <font color="red">$|010 \rangle $</font>, and the relevant <font color="blue">tensor products</font>. 


### Compute the following <font color="red">Action</font>(s): 

<BR>

0. $(X \otimes X \otimes Y)$ <font color="red">$|010 \rangle$</font>

0. $(X \otimes Z \otimes H)$ <font color="red">$|010 \rangle$</font>

0. $(H \otimes H \otimes H)$ <font color="red">$|010 \rangle$</font>

<BR>

### <font color="red">6</font>: <font color="black">$(X \otimes X \otimes Y)|010 \rangle$</font>
> - ### <font color="red">This one is done for you</font>.

### <font color="red">Reference</font>: Basis State - "<font color="blue">**|010>**</font>"

<BR>
<font color="blue">
    
\begin{align}
|010\rangle &= |0\rangle \otimes |1\rangle \otimes |0\rangle \\
&= \begin{pmatrix}
1\\0
\end{pmatrix} \otimes 
\begin{pmatrix}
0\\1
\end{pmatrix} \otimes 
\begin{pmatrix}
1\\0
\end{pmatrix} \\
&= \begin{pmatrix}
0\\0\\1\\0\\0\\0\\0\\0
\end{pmatrix}
\end{align}

</font>
<BR>

#### Define the basis state  <font color="red">|010></font>

In [34]:
# Define the basis state |010>

u = np.matrix([[1],
               [0]])

d = np.matrix([[0],
               [1]])

u = np.matrix([[1],
               [0]])

# Basis State "udu" (|010>)

udu = np.kron(np.kron(u,d),u)

udu

matrix([[0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0]])

#### Check shape

In [36]:
udu.shape

(8, 1)

#### Tensor Product: <font color="red">$(X \otimes X \otimes Y)$</font>

In [33]:
XXY = np.kron(np.kron(X, X),Y)
XXY

matrix([[0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j],
        [0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.-0.j, 0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j],
        [0.+0.j, 0.+0.j, 0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.-1.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j],
        [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

#### Check shape

In [37]:
XXY.shape

(8, 8)

####  <font color="red">Action</font>: <font color="black">$(X \otimes X \otimes Y)|010 \rangle$</font>

In [35]:
XXY * udu

matrix([[0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+0.j],
        [0.+1.j],
        [0.+0.j],
        [0.+0.j]])

### <font color="red">7</font>: <font color="black">$(X \otimes Z \otimes H)|010 \rangle$</font>

### <font color="red">8</font>: <font color="black">$(H \otimes H \otimes H)|010 \rangle$</font>

![the-end](img/the-end.png "the-end")